routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('/', 'ArticleController@home');



Route::get('/profile', 'PublicController@profile');

Route::post('/profile', 'MeasurementController@storedata');


Route::get('/logout','\App\Http\Controllers\Auth\LoginController@logout');


Route::get('/calendar', 'TasksController@index');



Route::get('/json-date','PublicController@autoload');



Route::resource('tasks', 'TasksController');


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/admin', 'AdminController@admin')
    ->middleware('is_admin')
    ->name('admin');
Route::post('/admin', 'AdminController@storeArticles');

Route::get('/admin/{post}/delete', 'AdminController@deletePost');
Route::get('/admin/{client}/delete', 'AdminController@deleteUser');

Route::get('/{post}/edit', 'AdminController@goEditArcticle');


Route::get('/full/{post}', 'ArticleController@showFull');

Route::get('/{client}/client-date', 'AdminController@goClient');
Route::get('/{client}/date', 'AdminController@goDate');
Route::get('/{time}/edit-task', 'AdminController@goEditTask');

Route::patch('/{post}', 'AdminController@update');
Route::patch('/{time}/edit-task', 'AdminController@updateTaskVer');

Route::patch('/{client}/date', 'AdminController@updateClients');
Route::get('/{client}/add', 'AdminController@goAdd');
Route::post('/{client}/add', 'AdminController@adminAddMea');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['user_id', 'ver', 'workout', 'task_date'];

}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\User;

use Illuminate\Http\Request;
use App\Task;

class TasksController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $tasks = Task::all();
        $id =  User::where('id', '=', Auth::id())->get();
        return view('pages.calendar', compact('tasks', 'id'));
    }

    public function create()
    {
        return view('tasks.create');
    }

    public function store(Request $request)
    {
            Task::create([
                'workout' => request('workout'),
                'task_date' => request('task_date'),
                'ver' => request('ver'),
                'user_id' => auth()->id(),

            ]);
            return back();
    }
//    public function edit($id)
//    {
//        $info= Task::where('user_id', '=', Auth::id())->get();
//        return view('pages.edit', compact( 'id', 'info'));
//    }


}

resources/views/tasks/create.blade.php
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!-- Minified JS library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Minified Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link href="css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<script src="js/bootstrap-datetimepicker.min.js"></script>
<script src='js//locales/bootstrap-datetimepicker.lt.js' type='text/javascript'></script>
<link rel="stylesheet" href="{{ asset('css/style.css') }}">

<section class="container sec-top-che sec-top sec-cal">
    <form action="{{ route('tasks.store') }}" method="post">
        {{ csrf_field() }}

        <div class="form-group row">
            <label for="workout" class="col-md-4 col-form-label text-md-right">Treniruotė</label>
            <div class="col-md-4">
                <select   name="workout" id="workout">
                    @foreach ($workouts = array('Kūno dizainas', 'Svorio metimas', 'Core', 'Cardio')  as $workout)
                        <option contenteditable="false"  value="{{$workout}}"> {{$workout}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="task_date" class="col-md-4 col-form-label text-md-right">Treniruotės data ir laikas:</label>

            <div class="col-md-4">
                <input  name="task_date" class="datetime2 "id="datetime2" contenteditable="false" required />
                <button type="submit"  id="button" class="btn btn-dark">Saugoti</button>
            </div>
        </div>

            <button  id="button" class="btn"  disabled style=" background: #008700; color: white; opacity: 1;"> Jūsų patvirtinta treniruotė</button>
            <button  id="button" class="btn"  disabled style=" background: #1e429e;  color: white; opacity: 1;">Jūsų nepatvirtinta treniruotė</button>
            <button  id="button" class="btn"  disabled style=" background: #ff2c27; opacity: 1;">Patvirtinta treniruotė</button>
            <button  id="button" class="btn" disabled style=" background: #ffbd7e; opacity: 1;">Nepatvirtinta treniruotė</button>


    </form>
    <hr>
</section>

    <script type="text/javascript">
        $("#datetime2").datetimepicker({
            language: 'lt',
            startDate: new Date(),
            format: 'yyyy-mm-dd hh:ii',
            autoclose: true,
        });

        document.addEventListener("DOMContentLoaded", function() {
            var elements = document.getElementsByTagName("INPUT");
            for (var i = 0; i < elements.length; i++) {
                elements[i].oninvalid = function(e) {
                    e.target.setCustomValidity("");
                    if (!e.target.validity.valid) {
                        e.target.setCustomValidity("Laukas negali būti tuščias");
                    }
                };
                elements[i].oninput = function(e) {
                    e.target.setCustomValidity("");
                };
            }
        })
    </script>

resources/views/tasks/index.blade.php
<section class="container sec-cal">
    <h3>Užsiėmimų kalendorius</h3>
    <div id='calendar'></div>

</section>

<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>
<script src='fullcalendar/locale/lt.js'></script>
<script>
    $(document).ready(function  showCalendar() {
        $('#calendar').fullCalendar({
            locale: 'lt',
            axisFormat: 'HH:mm',
            timeFormat: 'HH:mm',
            minTime: 0,
            maxTime: 24,

            events : [
                    @foreach($tasks as $task)
                {
                    title : '{{ $task->workout  }}' ,
                    start : '{{ $task->task_date }}',
                    className: '{{ $task->user_id }}',
                    id:'{{ $task->ver }}',

                },       @endforeach
            ],

            eventRender:
                @foreach($id as $dd)

                function(event, element) {
                if(event.className == '{{ $dd->id }}' && event.id == '{{ $dd->ver }}')
                 {
                    element.css({
                        'background-color': '#16279e',
                        'border-color': '#16279e'
                    });


                 }
                else if (event.className == '{{ $dd->id }}' && event.id != '{{ $dd->ver }}'){
                    element.css({
                        'background-color': '#008700',
                        'border-color': '#008700'
                    });
                }
                else if (event.className != '{{ $dd->id }}' && event.id == '{{ $dd->ver }}'){
                    element.css({
                        'background-color': '#ffbd7e',
                        'border-color': '#ffbd7e'
                    });
                }
                    else
                      {
                        element.css({
                            'background-color': '#ff2c27',
                            'border-color': '#ff2c27'
                        });
                    }
            }, @endforeach



        })
    });

</script>